name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          docker buildx create --name=b --driver docker-container
          docker buildx use b
          echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build images
        run: |
          docker buildx build --platform=arm64,amd64 -t ghcr.io/zoetrope/accurate:$TAG .
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Push images
        run: |
          docker buildx build --platform=arm64,amd64 -t ghcr.io/zoetrope/accurate:$TAG . --push
